resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: aoldershaw/github-pr-resource

resources:
- name: pull-request
  type: pull-request
  source:
    repository: bakunowski/go-retry
    access_token: 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
    number: ((pr-number))

jobs:
- name: test
  plan:
  - get: pull-request
    trigger: true
  - put: pull-request-status
    resource: pull-request
    params:
      path: pull-request
      status: pending
    get_params: {skip_download: true}
  - task: unit-test
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: alpine/git, tag: latest}
      inputs:
        - name: pull-request
      run:
        path: /bin/sh
        args:
          - -xce
          - |
            cd pull-request
            git log --graph -n 10 --color --pretty=format:"%x1b[31m%h%x09%x1b[32m%d%x1b[0m%x20%s" > log.txt
            cat log.txt
  on_success:
    put: update-status
    resource: pull-request
    params:
      path: pull-request
      status: success
    get_params: {skip_download: true}
  on_failure:
    put: update-status
    resource: pull-request
    params:
      path: pull-request
      status: failure
    get_params: {skip_download: true}
