resources:
  - name: home
    type: git
    source:
      uri: https://github.com/bakunowski/concourse-testing
      username: bakunowski
      password: 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

jobs:
- name: update-all-pipelines
  plan:
  - get: home
    trigger: true
  - load_var: config
    file: home/jobs.yml
  - across:
    - var: job
      values: ((.:config.jobs))
    set_pipeline: prs
    file: ci/ci/pipelines/pr-parent.yml
    instance_vars: {repo-name: ((.:job.name))}

    # do:  # takes a list of steps
    # - task: saying-hello
    #   config:
    #     platform: linux
    #     image_resource:
    #       type: mock
    #       source:
    #         mirror_self: true
    #     run:
    #       path: echo
    #       args: ["Hello ((.:job.name))!"]
