resources:
  - name: home
    type: git
    source:
      uri: https://github.com/bakunowski/concourse-testing
      username: bakunowski
      password: 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
      # TODO:
      # paths:

jobs:
- name: update-all-pipelines
  plan:
  - get: home
    trigger: true
  - load_var: config
    file: home/jobs.yml
  - across:
    - var: job
      values: ((.:config.jobs))
    do:
    - set_pipeline: ((.:job.name))
      file: home/update-prs.yml
      vars:
        repo-name: ((.:job.name))
        pipeline: ((.:job.pr))
      instance_vars:
        purpose: update-pr-pipelines
    - set_pipeline: ((.:job.name))
      file: home/pipelines/((.:job.master))
      instance_vars:
        purpose: master ci
