resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: aoldershaw/github-pr-resource

resources:
- name: pull-requests
  type: pull-request
  source:
    repository: bakunowski/((repo-name))
    access_token: ((github-token))

- name: home
  type: git
  source:
    uri: https://github.com/bakunowski/concourse-testing

jobs:
- name: update-pr-pipelines
  plan:
  - get: home
    trigger: true
  - get: pull-requests
    trigger: true
  - load_var: pull_requests
    file: pull-requests/prs.json
  - across:
    - var: pr
      values: ((.:pull_requests))
    set_pipeline: ((repo-name))
    file: home/pipelines/((pipeline))
    vars:
      repo-name: ((repo-name))
      github-token: ((github-token))
    instance_vars:
      pr-number: ((.:pr.number))
