---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: golang

inputs:
- name: source-code

run:
  path: /bin/sh
  args:
    - -ec
    - |
      cd source-code
      go test ./...
